Repository boldlink/terraform-aws-budget, pull requests merged in 2023-01, with the labels that each got.

#1 PR to add First AWS Budget (v1.0.0)
  .checkov.yml
  .github/workflows/auto-badge.yaml
  .github/workflows/checkov.yaml
  .github/workflows/pr-labeler.yaml
  .github/workflows/pre-commit.yaml
  .github/workflows/release.yaml
  CHANGELOG.md
  README.md
  data.tf
  examples/complete/README.md
  examples/complete/locals.tf
  examples/complete/main.tf
  examples/complete/versions.tf
  examples/minimum/README.md
  examples/minimum/locals.tf
  examples/minimum/main.tf
  examples/minimum/versions.tf
  main.tf
  modules/nestedA/README.md
  modules/nestedA/main.tf
  modules/nestedA/outputs.tf
  modules/nestedA/variables.tf
  modules/nestedA/versions.tf
  modules/nestedB/README.md
  modules/nestedB/main.tf
  modules/nestedB/outputs.tf
  modules/nestedB/variables.tf
  modules/nestedB/versions.tf
  outputs.tf
  variables.tf
  versions.tf
Labels: major

#2 [automation] updated files automatically.
  .github/workflows/auto-badge.yaml
  .github/workflows/checkov.yaml
  .github/workflows/pr-labeler.yaml
  .github/workflows/pre-commit.yaml
  .github/workflows/release.yaml
Labels: automerge

#3 modified the email used in examples
  CHANGELOG.md
  examples/complete/locals.tf
  examples/minimum/locals.tf
Labels: patch

#4 [automation] updated files automatically.
  .github/workflows/auto-badge.yaml
  .github/workflows/checkov.yaml
  .github/workflows/pr-labeler.yaml
  .github/workflows/pre-commit.yaml
  .github/workflows/release.yaml
  .github/workflows/update.yaml
  README.md
Labels: automerge
